namespace Foundation
{
    using System;
    using System.Runtime.Serialization;

    /// <summary>
    /// Exception type that encapsulates the error message generated by a failing <see cref="Response{T}"/>
    /// </summary>
    /// <seealso cref="Response{T}" />
    [Serializable]
    public class ResponseException : Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseException"/> class.
        /// </summary>
        public ResponseException()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseException"/> class.
        /// </summary>
        /// <param name="message">The message provided by <see cref="Response.Message"/></param>
        public ResponseException(string message) : base(message)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseException"/> class.
        /// </summary>
        /// <param name="message">The message provided by <see cref="Response.Message"/></param>
        /// <param name="inner">The inner exception.</param>
        public ResponseException(string message, Exception inner) : base(message, inner)
        {
        }

        protected ResponseException(
            SerializationInfo info,
            StreamingContext context) : base(info, context)
        {
        }
    }
}
